# Generated by Django 2.2.6 on 2019-10-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=20)),
                ('circuit_id', models.CharField(max_length=10)),
                ('connect_id', models.CharField(max_length=32)),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
