# Generated by Django 2.2.6 on 2019-10-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
